### ISSUE TITLE
How to delete the track?

### ISSUE THREAD

**Issue by martybalandis** [njasm/soundcloud#29]
After https://github.com/mptre/php-soundcloud stopped working after PHP 5.6 due to curl file with @ deprication and after fiddling and forking I gave up. I turned back to this libarary and got it to work (the uploading part at least) and I used:

use Njasm\Soundcloud\SoundcloudFacade 

to upload, and later on I found that delete available in it so I looked at source of:
use Njasm\Soundcloud\Soundcloud;

and saw that delete is there but it doesn't seem to work. 
The problem is I used Facade to connect and use the token I stored in database.

$facade = new SoundcloudFacade(SOUNDCLOUDCLIENTID, SOUNDCLOUDSECRET, SOUNDCLOUDREDIRECT);
$facade->setAccessToken($dbAccessToken);

so I do not have $soundcloud object  so I tried:

    $soundcloud = new Soundcloud(SOUNDCLOUDCLIENTID, SOUNDCLOUDSECRET);

    $response = $soundcloud->delete('/tracks/'.$sctid);  // $sctid is the track ID
    $response = $soundcloud->request();

but it doesn't seem to work. As I don't know how to set the token to the $soundcloud variable like I did with $facade. I know delete has 2 more parameters but I am not sure what to add there for delete part. It lacks documentation on this. More importantly any way to share the object between Facade and Soundcloud or the only way to ditch Facade all together and rewrite to just Soundcloud to reduce redundancy, if you know what I mean..

Any ideas would be helpful.

**Comment by njasm** [comment]
hello @martybalandis 
thanks for trying out the library.

``SoundcloudFacade`` is there because I feel that the methods it exposes, are on a different abstraction layer. I don't feel comfortable (at least right now to move those methods in the ``Soundcloud`` object).
but  I invite you (and everybody to convince me otherwise :) ).

Regarding the ``delete`` method, since ``SoundcloudFacade extend Soundcloud`` object and the ``delete`` method is public you have it available in the SoundcloudFacade object.

have you tried something like this:
```php
$facade = new SoundcloudFacade(SOUNDCLOUDCLIENTID, SOUNDCLOUDSECRET, SOUNDCLOUDREDIRECT);
$facade->setAccessToken($dbAccessToken);

$response = $facade->delete('/tracks/'.$sctid)->request();
```
can you var dump the response object and paste it here? (the headers and the Raw body)
What does soundcloud api is telling you?

Don't forget soundcloud have implemented some sort of micro/services architecture, your request might take some time to replicate to they frontend application.

**Comment by martybalandis** [comment]
Hi @njasm 

Thank you for quick reply. It does indeed work, I thought it was seperate and not extends, not it makes more sence.
